WALL_MAP = ['''\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
W.......W....WW...W..WW.....WW......WW..
WW.WWWWWW..W..W..WW.....W...W....WW....W
W..W...VW..W.WW...W..W..WWWWWWWWv.W.WW.W
WW.WWW..W..W....W....W......WW.V..W..W.W
WW...W....WW.WW.WW.WWW.WW....W...WWW...W
W..W...WW..VH.......W...WW..WWW........W
W.WWWWWW....W..WW..WWW..W....W..WWWWWWWW
W......WWW..W.WWWW....WW...WWWW...WWV..W
W..WWH......W....W.WW.....W.....WWW....W
WW.WWWW.WWW.W....W....WWWWW.......W....W
W........W..WWWWWW....W...W..WWW......HW
W..W..WWWW.....WH....WWWW....W....WWWWWW
W..WWWW.....WW.WWWW..WH.......W....W...W
WW....WWWW...WV..W..WWWWW..WWWW....W...W
Wh....W..W.WWW...WH.....W.....WWWWWW...W
WWWW..WW...W...WW..W..WWWWW...W..W.....W
W.....W...WW...W..W..W..VWW..WW.....WWWW
W...WWWWW...W...WWWWW.WW.WW...WWW.....VW
WWW...W.....WW......W....W.WW...WWWWWW.W
WH......WWWWW..WWW..WWWW......WV.....W.W
W..WWW..W......W...WW..W.W.WW.W..WWWWW.W
WP.........W...WH........W.W..W........W 
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
\
''',
            
'''\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WP......W....WW......WW.....WW......WW.W
WW.WW.WWW..W..W..WW.....W...W....WW....W
W...W..VW..W.WW...W..W..WWWWWWWWv.W.WW.W
WW..W......W....W....W.....HWW.V..W....W
WW...WW.WWWWW.WW.WW.WWW.WW....W...WWW..W
W..W....W...H.......W...WW..WWW........W
W.WW........W...W..WWW..W....W..WWWW.WWW
W......WWW..W.WWWW....WW....WWW...WWV..W
W..WWH......W....W.WW.....W.....WWW....W
WW.WWWWWWWW.W....W....WWWWW.......W....W
W......VW..W...WW....W...W..WW.....W..HW
W..W.......W.W.WWW...WWWW....W....WWWWWW
W..WWWW......W.WWWW..WH.......W....W...W
WW....WWWW...WV..WWWWWWWW..WWWWW..WW...W
Wh....W..W.WWW...WH.....W.....WWWWWWWW.W
WWWW..WW...W...WW..W..WWWWW...W..W.....W
W.....W...WW...W..W..W..VWW..WW.....WWWW
W...WWWWW...W...WWWWW.WW.WW...WWW.....VW
WWW...W.....WW......W....W.WW...W.WWWW.W
WH...WWW..WWW..WWW..WWWWH............W.W
W..WWW..W......W...WW..W.W...WW..WW.WW.W
W......W...WH........W.W...W............
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
\
''' ,

'''\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WP......W....WW......WW.....WW......WW.W
WW.WW.WWW..W..W..WW.....W...W....WW....W
W...W..VW..W.WW...W..W..WWWWWWWWv.W.WW.W
WW..W......W....W....W.....HWW.V..W....W
WW...WW.WWWWW.WW.WW.WWW.WW....W...WWW..W
W..W....W...H.......W...WW..WWW........W
W.WW........W...W..WWW..W....W..WWWW.WWW
W......WWW..W.WWWW....WW....WWW...WWV..W
W..WWH......W....W.WW.....W.....WWW....W
WW.WWWWWWWW.W....W....WWWWW.......W....W
W......VW..W...WW....W...W..WW.....W..HW
W..W.......W.W.WWW...WWWW....W....WWWWWW
W..WWWW......W.WWWW..WH.......W....W...W
WW....WWWW...WV..WWW.WWWW..WWWWW..WW...W
Wh....W..W.WWW...WH.....W.....WWWWWWWW.W
WWWW..WW...W...WW..W..WWWWW...W..W.....W
W.....W...WW...W..W..W..VWW..WW.....WWWW
W...WWWWW...W...WWWWW.WW.WW...WWW.....VW
WWW...W.....WW......W....W.WW...W.WWWW.W
WH...WWW..WWW..WWW..WWWWH............W.W
W..WWW..W......W...WW..W.W...WW..WW.WW.W
W......W...WH........W.W...W............
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
\
''' ,

'''\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
W.......W....WW...W.VWW.....WW......WW..
WW.WWWWWW..W..W..WW.....W..H.....WW....W
W..W...VW..W.WW...W..WV.WWWWWWWWv.W.WW.W
WW.WWW..W..W...VW....W....V.WW.V..W..W.W
WW...W....WW.WW.WW.WWW.WW....W...WWW...W
W..W...WW..VH.......W...WW..WWW........W
W.WWWWWW....W..WW..WWW..W....W..WWWWWWVW
W......WWW..W.WWWW....WW...WWWW...WWV..W
W..WWH......W....W.WW.....WV....WWW....W
WW.WWWW.WWW.W....W....WWWWW.......W....W
W...H....W..WWWWWW.......W..WWW......HW
W..W..WWWW.....WH....WWWW....W....WWWWWW
W..WWWW.....WW.WWWW..WH.......W....W...W
WW..H.WWWW...WV..W..WWWWW..WWWW....W...W
Wh....W..W.WWW...WH.....W.....WWWWWW...W
WWWW..WW...W...WW..W..WWWWW...W..W.....W
W..H..W...WW...W..W..W..VWW..WW.....WWWW
W...WWWWW...W...WWWWW.WW.WW...WWW.....VW
WWW...W.....WW......W....W.WW...WWWWWW.W
WH......WWWWW..WWW..WWWW......WV.....W.W
W..WWW..W......W...WW..W.W.WW.W..WWWWW.W
WP......W..W...WH....W...W.W..W........W
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
\
''' 
]
